<?php

function base64url_encode($input) {
    return strtr(base64_encode($input), '+/', '-_');
}

  $id = $_GET['id'];

if(isset($_GET['finvoice'])){

if($lasku['tyyppi'] == 'yritys')
$BuyerOrganisationName = $lasku['yritys'];
if($lasku['tyyppi'] == 'henkilo')
$BuyerOrganisationName = $lasku['nimi'];

if($lasku['tyyppi'] == 'yritys')
$BuyerContactPersonName = $lasku['yhteyshenkilo'];
if($lasku['tyyppi'] == 'henkilo')
$BuyerContactPersonName = $lasku['nimi'];

$xml = '<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Jussi Paasikallio (OKOBANK Group) -->
<!--Sample XML file generated by XML Spy v4.2 U (http://www.xmlspy.com)-->
<!DOCTYPE Finvoice SYSTEM "Finvoice.dtd">
<?xml-stylesheet type="text/xsl" href="Finvoice.xsl"?>
<!--Finvoice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Finvoice.xsd" Version="1.2"-->
<Finvoice Version="1.2">
<SellerPartyDetails>
<SellerPartyIdentifier>'.$yritys['y_tunnus'].'</SellerPartyIdentifier>
<SellerOrganisationName>'.$yritys['tyonantaja'].'</SellerOrganisationName>
<SellerOrganisationTaxCode>'.$yritys['y_tunnus'].'</SellerOrganisationTaxCode>
<SellerOrganisationTaxCodeUrlText>http://etunti.fi</SellerOrganisationTaxCodeUrlText>
<SellerPostalAddressDetails>
<SellerStreetName>'.$yritys['osoite'].'</SellerStreetName>
<SellerTownName>'.$yritys['postitoimipaikka'].'</SellerTownName>
<SellerPostCodeIdentifier>'.$yritys['postinumero'].'</SellerPostCodeIdentifier>
</SellerPostalAddressDetails>
</SellerPartyDetails>
<SellerContactPersonName>'.$yritys['johtaja'].'</SellerContactPersonName>
<SellerCommunicationDetails>
<SellerEmailaddressIdentifier>'.$yritys['sahkoposti'].'</SellerEmailaddressIdentifier>
</SellerCommunicationDetails>
<SellerInformationDetails>
<SellerHomeTownName>'.$yritys['postitoimipaikka'].'</SellerHomeTownName>
<SellerPhoneNumber>'.$yritys['puhelin'].'</SellerPhoneNumber>
<SellerFaxNumber></SellerFaxNumber>
<SellerCommonEmailaddressIdentifier>'.$yritys['sahkoposti'].'</SellerCommonEmailaddressIdentifier>
<SellerWebaddressIdentifier></SellerWebaddressIdentifier>
<SellerFreeText></SellerFreeText>
<SellerAccountDetails>
<SellerAccountID IdentificationSchemeName="IBAN">'.$asetukset['iban'].'</SellerAccountID>
<SellerBic IdentificationSchemeName="BIC">'.$asetukset['bic'].'</SellerBic>
</SellerAccountDetails>
<InvoiceRecipientDetails>
<InvoiceRecipientAddress>'.$lasku['osoite'].'</InvoiceRecipientAddress>
<InvoiceRecipientIntermediatorAddress></InvoiceRecipientIntermediatorAddress>
</InvoiceRecipientDetails>
</SellerInformationDetails>
<InvoiceSenderPartyDetails>
<InvoiceSenderPartyIdentifier>'.$yritys['y_tunnus'].'</InvoiceSenderPartyIdentifier>
<InvoiceSenderOrganisationName>'.$yritys['tyonantaja'].'</InvoiceSenderOrganisationName>
</InvoiceSenderPartyDetails>
<InvoiceRecipientPartyDetails>
<InvoiceRecipientPartyIdentifier/>
<InvoiceRecipientOrganisationName>'.$lasku['yritys'].'</InvoiceRecipientOrganisationName>
<InvoiceRecipientPostalAddressDetails>
<InvoiceRecipientStreetName>'.$lasku['osoite'].'</InvoiceRecipientStreetName>
<InvoiceRecipientTownName>'.$lasku['toimipaikka'].'</InvoiceRecipientTownName>
<InvoiceRecipientPostCodeIdentifier>'.$lasku['postinumero'].'</InvoiceRecipientPostCodeIdentifier>
<CountryCode>FI</CountryCode>
<CountryName>FINLAND</CountryName>
<InvoiceRecipientPostOfficeBoxIdentifier></InvoiceRecipientPostOfficeBoxIdentifier>
</InvoiceRecipientPostalAddressDetails>
</InvoiceRecipientPartyDetails>
<BuyerPartyDetails>
<BuyerPartyIdentifier>'.$lasku['as_nro'].'</BuyerPartyIdentifier>
<BuyerOrganisationName>'.$BuyerOrganisationName.'</BuyerOrganisationName>
<BuyerOrganisationTaxCode>'.$lasku['y_tunnus'].'</BuyerOrganisationTaxCode>
<BuyerPostalAddressDetails>
<BuyerStreetName>'.$lasku['osoite'].'</BuyerStreetName>
<BuyerTownName>'.$lasku['toimipaikka'].'</BuyerTownName>
<BuyerPostCodeIdentifier>'.$lasku['postinumero'].'</BuyerPostCodeIdentifier>
</BuyerPostalAddressDetails>
</BuyerPartyDetails>
<BuyerContactPersonName>'.$BuyerContactPersonName.'</BuyerContactPersonName>
<BuyerCommunicationDetails>
<BuyerPhoneNumberIdentifier>'.$lasku['puhelin'].'</BuyerPhoneNumberIdentifier>
<BuyerEmailaddressIdentifier>'.$lasku['sahkoposti'].'</BuyerEmailaddressIdentifier>
</BuyerCommunicationDetails>
<DeliveryPartyDetails>
<DeliveryPartyIdentifier/>
<DeliveryOrganisationName>'.$lasku['t_yritys'].'</DeliveryOrganisationName>
<DeliveryPostalAddressDetails>
<DeliveryStreetName>'.$lasku['t_osoite'].'</DeliveryStreetName>
<DeliveryTownName>'.$lasku['t_toimipaikka'].'</DeliveryTownName>
<DeliveryPostCodeIdentifier>'.$lasku['t_postinumero'].'</DeliveryPostCodeIdentifier>
<DeliveryPostofficeBoxIdentifier/>
</DeliveryPostalAddressDetails>
</DeliveryPartyDetails>
<DeliveryDetails>
<DeliveryDate Format="CCYYMMDD">'.date("Ymd").'</DeliveryDate>
<DeliveryMethodText></DeliveryMethodText>
<DeliveryTermsText></DeliveryTermsText>
<TerminalAddressText></TerminalAddressText>
<WaybillIdentifier></WaybillIdentifier>
<WaybillTypeCode></WaybillTypeCode>
<DelivererIdentifier></DelivererIdentifier>
<DelivererName></DelivererName>
<DelivererCountryCode></DelivererCountryCode>
<DelivererCountryName></DelivererCountryName>
<ManufacturerIdentifier></ManufacturerIdentifier>
<ManufacturerName></ManufacturerName>
<ManufacturerCountryCode></ManufacturerCountryCode>
<ManufacturerCountryName>Germany</ManufacturerCountryName>
</DeliveryDetails>
<InvoiceDetails>
<InvoiceTypeCode>INV01</InvoiceTypeCode>
<InvoiceTypeText>LASKU</InvoiceTypeText>
<OriginCode>Original</OriginCode>
<InvoiceNumber>'.$lasku['id'].'</InvoiceNumber>
<InvoiceDate Format="CCYYMMDD">'.date("Ymd",strtotime($lasku['paivays'])).'</InvoiceDate>
<SellerReferenceIdentifier></SellerReferenceIdentifier>
<OrderIdentifier></OrderIdentifier>
<InvoiceTotalVatExcludedAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",$lasku['yhteensa_total_veroton']).'</InvoiceTotalVatExcludedAmount>
<InvoiceTotalVatAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",$lasku['yhteensa_total_verot']).'</InvoiceTotalVatAmount>
<InvoiceTotalVatIncludedAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",$lasku['yhteensa_total']).'</InvoiceTotalVatIncludedAmount>
<VatSpecificationDetails>
<VatBaseAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",$lasku['yhteensa_total_veroton']).'</VatBaseAmount>
<VatRatePercent>22</VatRatePercent>
<VatRateAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",$lasku['yhteensa_total_verot']).'</VatRateAmount>
</VatSpecificationDetails>
<PaymentTermsDetails>
<PaymentTermsFreeText>'.$lasku['maksuehto'].' pv</PaymentTermsFreeText>
<InvoiceDueDate Format="CCYYMMDD">'.date("Ymd",strtotime($lasku['erapaiva'])).'</InvoiceDueDate>
<CashDiscountDate Format="CCYYMMDD"></CashDiscountDate>
<CashDiscountBaseAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",$lasku['yhteensa_total']).'</CashDiscountBaseAmount>
<CashDiscountPercent>2</CashDiscountPercent>
<CashDiscountAmount AmountCurrencyIdentifier="EUR"></CashDiscountAmount>
<PaymentOverDueFineDetails>
<PaymentOverDueFineFreeText>Viivästyskorko '.$lasku['viivastyskorko'].'%</PaymentOverDueFineFreeText>
<PaymentOverDueFinePercent>'.$lasku['viivastyskorko'].'</PaymentOverDueFinePercent>
</PaymentOverDueFineDetails>
</PaymentTermsDetails>
</InvoiceDetails>
<PaymentStatusDetails>
<PaymentStatusCode>PARTLYPAID</PaymentStatusCode>
</PaymentStatusDetails>
<VirtualBankBarcode>257800750155447003352980000000000000200448604122900008</VirtualBankBarcode>';

foreach($laskunRivit as $rivi){
$xml .= '<InvoiceRow>
<RowSubIdentifier></RowSubIdentifier>
<ArticleIdentifier></ArticleIdentifier>
<ArticleName>'.$rivi['tkoodi'].'</ArticleName>
<DeliveredQuantity QuantityUnitCode="kpl">'.$rivi['kpl'].'</DeliveredQuantity>
<OrderedQuantity QuantityUnitCode="kpl">'.$rivi['kpl'].'</OrderedQuantity>
<UnitPriceAmount AmountCurrencyIdentifier="EUR">'.$rivi['hinta'].'</UnitPriceAmount>
<RowIdentifier></RowIdentifier>
<RowDeliveryDate Format="CCYYMMDD"></RowDeliveryDate>
<RowAgreementIdentifier></RowAgreementIdentifier>
<RowRequestOfQuotationIdentifier></RowRequestOfQuotationIdentifier>
<RowPriceListIdentifier></RowPriceListIdentifier>
<RowDeliveryDetails>
<RowWaybillIdentifier></RowWaybillIdentifier>
<RowDelivererIdentifier></RowDelivererIdentifier>
<RowDelivererName></RowDelivererName>
<RowDelivererName></RowDelivererName>
<RowDelivererCountryCode></RowDelivererCountryCode>
<RowDelivererCountryName></RowDelivererCountryName>
<RowManufacturerIdentifier></RowManufacturerIdentifier>
<RowManufacturerName></RowManufacturerName>
<RowManufacturerCountryCode></RowManufacturerCountryCode>
<RowManufacturerCountryName></RowManufacturerCountryName>
</RowDeliveryDetails>
<RowShortProposedAccountIdentifier></RowShortProposedAccountIdentifier>
<RowNormalProposedAccountIdentifier></RowNormalProposedAccountIdentifier>
<RowFreeText></RowFreeText>
<RowVatRatePercent></RowVatRatePercent>
<RowVatAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",($rivi['yhteensa_alv']-$rivi['veroton'])).'</RowVatAmount>
<RowVatExcludedAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",$rivi['veroton']).'</RowVatExcludedAmount>
<RowAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",$rivi['yhteensa_alv']).'</RowAmount>
</InvoiceRow>';
}

$xml .= '<EpiDetails>
<EpiIdentificationDetails>
<EpiDate Format="CCYYMMDD">'.$lasku['erapaiva'].'</EpiDate>
<EpiReference>2004486</EpiReference>
</EpiIdentificationDetails>
<EpiPartyDetails>
<EpiBfiPartyDetails>
<EpiBfiIdentifier IdentificationSchemeName="BIC">'.$asetukset['bic'].'</EpiBfiIdentifier>
</EpiBfiPartyDetails>
<EpiBeneficiaryPartyDetails>
<EpiNameAddressDetails>'.$yritys['tyonantaja'].'</EpiNameAddressDetails>
<EpiBei></EpiBei>
<EpiAccountID IdentificationSchemeName="BBAN">'.$asetukset['tilinumero'].'</EpiAccountID>
</EpiBeneficiaryPartyDetails>
</EpiPartyDetails>
<EpiPaymentInstructionDetails>
<EpiRemittanceInfoIdentifier IdentificationSchemeName="SPY">'.$lasku['viitenumero'].'</EpiRemittanceInfoIdentifier>
<EpiInstructedAmount AmountCurrencyIdentifier="EUR">'.str_replace(".",",",$lasku['yhteensa_total']).'</EpiInstructedAmount>
<EpiCharge ChargeOption="SHA">SHA</EpiCharge>
<EpiDateOptionDate Format="CCYYMMDD">'.$lasku['erapaiva'].'</EpiDateOptionDate>
</EpiPaymentInstructionDetails>
</EpiDetails>
<InvoiceUrlNameText></InvoiceUrlNameText>
<InvoiceUrlNameText></InvoiceUrlNameText>
<InvoiceUrlText></InvoiceUrlText>
<InvoiceUrlText></InvoiceUrlText>
</Finvoice>';




if(!empty($asetukset['postita_username']) and !empty($asetukset['postita_password']))
{
$username = $asetukset['postita_username'];
$password = $asetukset['postita_password'];
$auth_string = $username . ":" . $password;


$account_info_url = 'https://postita.fi/api/account_info/';
$send_url = 'https://postita.fi/api/send/';
$send_finvoice_url = 'https://'.$auth_string.'@postita.fi/api/send_finvoice/';

$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_URL, $account_info_url);
curl_setopt($ch, CURLOPT_USERPWD, $auth_string);
curl_setopt($ch, CURLOPT_FAILONERROR, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 100);

$account_info = curl_exec($ch);
$account_info = json_decode($account_info, true);

  $prep = array();
  if(isset($account_info[0]))
  {
    foreach($account_info as $k => $v ) {
      $prep[$k] = $k.":".$v;
    }
  }

echo '<pre>';
print_r($account_info);
echo '</pre>';

$pdf = $xml;
$pdf_b64 = base64url_encode($pdf);

$data = array('job_name' => 'A letter from PHP curl API', 'pdf' => $pdf_b64);
curl_setopt($ch, CURLOPT_URL, $send_finvoice_url);
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:')); 

$send_response = curl_exec($ch);
if (curl_errno($ch)) {
  echo "\n\ncURL error number: " . curl_errno($ch);
  echo "\n\ncURL error: " . curl_error($ch);
}
$send_response = json_decode($send_response, true);

echo '<pre>';
print_r($send_response);
echo '</pre>';

curl_close($ch);

  if(isset($send_response[0]['status']) and $send_response[0]['status'] == 'CO')
  {

     foreach($send_response[0] as $k => $v ) {
       $prep[$k] = $k.":".$v;
     }
     Lasku::model()->updatebypk($id, array('tilanne'=>2,'response_finvoice'=>implode('//',$prep)));
     $this->redirect(array('update','id'=>$id));

  }


} else { 
	echo 'POSTITA tunnukset ei löydy';
} //if /pass


/*

$file = "tiedostot/finvoice/report.xml";
file_put_contents($file, $xml); 


header('Content-type: application/xml');
header('Content-Disposition: inline; filename="report.xml"');
@readfile($file);
*/
	//unlink($file);


}





if(isset($_GET['pdf'])){

if(!empty($asetukset['postita_username']) and !empty($asetukset['postita_password']))
{
$username = $asetukset['postita_username'];
$password = $asetukset['postita_password'];
$auth_string = $username . ":" . $password;


$account_info_url = 'https://postita.fi/api/account_info/';
$send_url = 'https://postita.fi/api/send/';
$send_finvoice_url = 'https://'.$auth_string.'@postita.fi/api/send_finvoice/';

/* First initialize curl and set some options. For more information about
   curl with PHP refer to http://php.net/manual/en/book.curl.php */
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_URL, $account_info_url);
curl_setopt($ch, CURLOPT_USERPWD, $auth_string);
curl_setopt($ch, CURLOPT_FAILONERROR, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 100);

/* Getting account info */
$account_info = curl_exec($ch);
$account_info = json_decode($account_info, true);

  $prep = array();
  if(isset($account_info[0]))
  {
    foreach($account_info as $k => $v ) {
      $prep[$k] = $k.":".$v;
    }
  }

echo '<pre>';
print_r($account_info);
echo '</pre>';


  $asetukset=Asetukset::model()->find("id=1");
  $firmanTiedot=FirmanTiedot::model()->find("id=1");

  $html2pdf = Yii::app()->ePdf->HTML2PDF('P', 'A4', 'en');
  $html2pdf->setDefaultFont('Arial');
  $html2pdf->WriteHTML($this->renderPartial('lasku_pdf', 
			array(
			'lasku'=>$lasku,
			'asetukset'=>$asetukset,
			'laskunRivit'=>$laskunRivit,
			'yritys'=>$firmanTiedot,
			),true));


  $content_PDF = $html2pdf->Output('my_doc.pdf', EYiiPdf::OUTPUT_TO_STRING);

$pdf = $content_PDF;
$pdf_b64 = base64url_encode($pdf);

$data = array('job_name' => 'A letter from PHP curl API', 'pdf' => $pdf_b64);
curl_setopt($ch, CURLOPT_URL, $send_url);
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:')); 

$send_response = curl_exec($ch);
if (curl_errno($ch)) {
  echo "\n\ncURL error number: " . curl_errno($ch);
  echo "\n\ncURL error: " . curl_error($ch);
}
$send_response = json_decode($send_response, true);

echo '<pre>';
print_r($send_response);
echo '</pre>';

curl_close($ch);


  if($send_response['status'] == 'CO')
  {

     foreach($send_response as $k => $v ) {
       $prep[$k] = $k.":".$v;
     }
     Lasku::model()->updatebypk($id, array('tilanne'=>2,'response'=>implode('//',$prep)));
     $this->redirect(array('update','id'=>$id));

  }

} else { 
	echo 'POSTITA tunnukset ei löydy';
} //if /pass

}






?>
