<?php

/**
 * This is the model class for table "laskut".
 *
 * The followings are the available columns in table 'laskut':
 * @property integer $id
 * @property integer $lid
 * @property integer $yid
 * @property string $time
 * @property string $tyyppi
 * @property string $yritys
 * @property string $y_tunnus
 * @property string $nimi
 * @property integer $as_nro
 * @property string $osoite
 * @property string $postinumero
 * @property string $toimipaikka
 * @property string $laskutus
 * @property string $sahkoposti
 * @property string $verkkolaskuosoite
 * @property string $v_tunnus
 * @property string $yhteyshenkilo
 * @property string $nimitarkenne
 * @property string $puhelin
 * @property string $t_yritys
 * @property string $t_y_tunnus
 * @property string $t_nimi
 * @property string $t_osoite
 * @property string $t_postinumero
 * @property string $t_toimipaikka
 * @property string $t_puhelin
 * @property string $t_sahkoposti
 * @property string $toimitusosoite
 * @property string $paivays
 * @property string $erapaiva
 * @property string $toimituspaiva
 * @property string $maksuehto
 * @property string $viitenumero
 * @property string $viitemme
 * @property string $viitenne
 * @property string $viivastyskorko
 * @property string $yhteensa_total_verot
 * @property string $yhteensa_total_veroton
 * @property string $yhteensa_total
 * @property string $saaja_iban
 * @property string $saaja_virtualkoodi
 * @property string $tilanne
 * @property string $maksettu_euro
 * @property string $hyvityslasku
 * @property string $laskun_nimetys
 * @property integer $procountor_id
 * Invoice ID in Procountor. This is generated by Procountor when sending an
 * invoice through the API. This happens when approving an invoice.
 */
class Lasku extends DB2ActiveRecord
{

	public $digisten_tunnit_id, $edico_tilaus_id, $count;

	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Lasku the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		$tb_name = 'laskut';
		$check_this_table = true;

		if($check_this_table)
		{
		$table = Yii::app()->db1->schema->getTable($tb_name);
		if(!isset($table->columns['id'])) {

			Yii::app()->db1->createCommand(" CREATE TABLE IF NOT EXISTS $tb_name 
			(`id` int(11) AUTO_INCREMENT PRIMARY KEY)
			")->execute();
		}

		$table_structure = array(
			'lid' => 'int(11) DEFAULT 0',
			'yid' => 'int(11) DEFAULT 0',
			'time' => 'timestamp DEFAULT CURRENT_TIMESTAMP',
			'tyyppi' => 'varchar(100) DEFAULT NULL',
			'yritys' => 'varchar(100) DEFAULT NULL',
			'y_tunnus' => 'varchar(50) DEFAULT NULL',
			'nimi' => 'varchar(100) DEFAULT NULL',
			'as_nro' => 'int(11) DEFAULT 0',
			'osoite' => 'varchar(255) DEFAULT NULL',
			'postinumero' => 'varchar(10) DEFAULT NULL',
			'toimipaikka' => 'varchar(50) DEFAULT NULL',
			'laskutus' => 'varchar(50) DEFAULT NULL',
			'sahkoposti' => 'varchar(100) DEFAULT NULL',
			'verkkolaskuosoite' => 'varchar(255) DEFAULT NULL',
			'v_tunnus' => 'varchar(100) DEFAULT NULL',
			'yhteyshenkilo' => 'varchar(100) DEFAULT NULL',
			'nimitarkenne' => 'varchar(100) DEFAULT NULL',
			'puhelin' => 'varchar(50) DEFAULT NULL',
			't_yritys' => 'varchar(100) DEFAULT NULL',
			't_y_tunnus' => 'varchar(50) DEFAULT NULL',
			't_nimi' => 'varchar(100) DEFAULT NULL',
			't_osoite' => 'varchar(100) DEFAULT NULL',
			't_postinumero' => 'varchar(10) DEFAULT NULL',
			't_toimipaikka' => 'varchar(100) DEFAULT NULL',
			't_puhelin' => 'varchar(50) DEFAULT NULL',
			't_sahkoposti' => 'varchar(100) DEFAULT NULL',
			'toimitusosoite' => 'varchar(100) DEFAULT NULL',
			'paivays' => 'varchar(20) DEFAULT NULL',
			'erapaiva' => 'varchar(20) DEFAULT NULL',
			'toimituspaiva' => 'varchar(20) DEFAULT NULL',
			'maksuehto' => 'varchar(20) DEFAULT NULL',
			'viitenumero' => 'varchar(100) DEFAULT NULL',
			'viivastyskorko' => 'varchar(50) DEFAULT NULL',
			'yhteensa_total_verot' => 'varchar(20) DEFAULT NULL',
			'yhteensa_total_veroton' => 'varchar(20) DEFAULT NULL',
			'yhteensa_total' => 'varchar(20) DEFAULT NULL',
			'saaja_iban' => 'varchar(100) DEFAULT NULL',
			'saaja_virtualkoodi' => 'varchar(255) DEFAULT NULL',
			'tilanne' => 'varchar(50) DEFAULT NULL',
			'maksettu_euro' => 'varchar(100) DEFAULT NULL',
			'hyvityslasku' => 'varchar(20) DEFAULT NULL',
			'laskun_nimetys' => 'varchar(100) DEFAULT NULL',
			'response' => 'text DEFAULT NULL',
			'response_finvoice' => 'text DEFAULT NULL',
			'postita_jobid' => 'varchar(100) DEFAULT NULL',
			'trust_jobid' => 'varchar(100) DEFAULT NULL',
			'tapahtumapvm' => 'varchar(50) DEFAULT NULL',
			'laskunumero' => 'varchar(11) DEFAULT NULL',
			'muistutuslasku_auto' => 'int(1) DEFAULT 0',
			'kirjeenluokka' => 'int(1) DEFAULT 0',
			'viitenne' => 'varchar(255) DEFAULT NULL',
			'viitemme' => 'varchar(255) DEFAULT NULL',
			'freetext' => 'varchar(255) DEFAULT NULL',
			'deliverymethod' => 'varchar(255) DEFAULT NULL',
			'deliveryterm' => 'varchar(255) DEFAULT NULL',
			'vatperiod' => 'varchar(50) DEFAULT NULL',
			'netvisorkey' => 'int(11) DEFAULT 0',
			'netvisor_dimension_name' => 'varchar(100) DEFAULT NULL',
			'netvisor_dimension_item' => 'varchar(100) DEFAULT NULL',
			'tuotteet_palvelut_muoto' => 'int(1) DEFAULT 0',
			'alv_muoto' => 'int(1) DEFAULT 0',
			'valmistettu_automaattiseesti' => 'int(1) DEFAULT 0',
			'procountor_id' => 'int(11) DEFAULT 0',
			'etunti_tunniste' => 'varchar(255) DEFAULT NULL',
		);

		foreach($table_structure as $key=>$value)
		{
			if (!isset($table->columns[$key])) {
				Yii::app()->db1->createCommand()->addColumn($tb_name, $key, $value);
			}
		}	
		} // if($check_this_table)

		return $tb_name;
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
                        //array('laskunumero','unique', 'message'=>'Tämä laskunumero on jo olemassa!'),
			array('yid, tyyppi, as_nro, osoite, postinumero, toimipaikka, laskutus, paivays, erapaiva, maksuehto, toimitusosoite', 'required'),
			array('kirjeenluokka, muistutuslasku_auto, lid, yid, as_nro, laskunumero, netvisorkey, tuotteet_palvelut_muoto, alv_muoto, valmistettu_automaattiseesti', 'numerical', 'integerOnly'=>true),
			array('tyyppi, yritys, nimi, sahkoposti, v_tunnus, yhteyshenkilo, nimitarkenne, t_yritys, t_nimi, t_osoite, t_toimipaikka, t_sahkoposti, toimitusosoite, viitenumero, saaja_iban, maksettu_euro, laskun_nimetys, postita_jobid, trust_jobid, netvisor_dimension_name, netvisor_dimension_item', 'length', 'max'=>100),
			array('vatperiod, y_tunnus, toimipaikka, laskutus, puhelin, t_y_tunnus, t_puhelin, viivastyskorko, tilanne, tapahtumapvm', 'length', 'max'=>50),
			array('deliverymethod, deliveryterm, freetext, viitenne, viitemme, osoite, verkkolaskuosoite, saaja_virtualkoodi', 'length', 'max'=>255),
			array('postinumero, t_postinumero', 'length', 'max'=>10),
			array('paivays, erapaiva, toimituspaiva, maksuehto, yhteensa_total_verot, yhteensa_total_veroton, yhteensa_total, hyvityslasku', 'length', 'max'=>20),
			array('response, response_finvoice, etunti_tunniste', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, lid, yid, time, tyyppi, yritys, y_tunnus, nimi, as_nro, osoite, postinumero, toimipaikka, laskutus, sahkoposti, verkkolaskuosoite, v_tunnus, yhteyshenkilo, nimitarkenne, puhelin, t_yritys, t_y_tunnus, t_nimi, t_osoite, t_postinumero, t_toimipaikka, t_puhelin, t_sahkoposti, toimitusosoite, paivays, erapaiva, toimituspaiva, maksuehto, viitenumero, viivastyskorko, yhteensa_total_verot, yhteensa_total_veroton, yhteensa_total, saaja_iban, saaja_virtualkoodi, tilanne, maksettu_euro, hyvityslasku, laskun_nimetys, response, response_finvoice, tapahtumapvm, kirjeenluokka, muistutuslasku_auto, freetext, viitenne, viitemme, vatperiod', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		        'asiakkaat' => array(self::BELONGS_TO, 'Asiakkaat', array('as_nro'=>'asiakasnumero')),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('main', 'ID'),
			'laskunumero' => Yii::t('main', 'Laskunumero'),
			'lid' => Yii::t('main', 'Lid'),
			'yid' => Yii::t('main', 'Saaja'),
			'time' => Yii::t('main', 'Luotu'),
			'tyyppi' => Yii::t('main', 'Tyyppi'),
			'yritys' => Yii::t('main', 'Yritys'),
			'y_tunnus' => Yii::t('main', 'Y-tunnus'),
			'nimi' => Yii::t('main', 'Nimi'),
			'as_nro' => Yii::t('main', 'Asiakas'),
			'osoite' => Yii::t('main', 'Osoite'),
			'postinumero' => Yii::t('main', 'Postinumero'),
			'toimipaikka' => Yii::t('main', 'Toimipaikka'),
			'laskutus' => Yii::t('main', 'Laskutus'),
			'sahkoposti' => Yii::t('main', 'Sahkoposti'),
			'verkkolaskuosoite' => Yii::t('main', 'Verkkolaskuosoite'),
			'v_tunnus' => Yii::t('main', 'Välittäjän tunnus'),
			'yhteyshenkilo' => Yii::t('main', 'Yhteyshenkilö'),
			'nimitarkenne' => Yii::t('main', 'Nimitarkenne'),
			'puhelin' => Yii::t('main', 'Puhelin'),
			't_yritys' => Yii::t('main', 'Toimitus Yritys'),
			't_y_tunnus' => Yii::t('main', 'Toimitus Y-tunnus'),
			't_nimi' => Yii::t('main', 'Toimitus Nimi'),
			't_osoite' => Yii::t('main', 'Toimitus Osoite'),
			't_postinumero' => Yii::t('main', 'Toimitus Postinumero'),
			't_toimipaikka' => Yii::t('main', 'Toimitus Toimipaikka'),
			't_puhelin' => Yii::t('main', 'Toimitus Puhelin'),
			't_sahkoposti' => Yii::t('main', 'Toimitus Sähköposti'),
			'toimitusosoite' => Yii::t('main', 'Toimitusosoite on eri kuin laskutusosoite'),
			'paivays' => Yii::t('main', 'Päiväys'),
			'erapaiva' => Yii::t('main', 'Eräpäivä'),
			'toimituspaiva' => Yii::t('main', 'Toimituspäivä'),
			'maksuehto' => Yii::t('main', 'Maksuehto'),
			'viitenumero' => Yii::t('main', 'Viitenumero'),
			'viivastyskorko' => Yii::t('main', 'Viivästyskorko'),
			'yhteensa_total_verot' => Yii::t('main', 'Yhteensa Total Verot'),
			'yhteensa_total_veroton' => Yii::t('main', 'Yhteensa Total Veroton'),
			'yhteensa_total' => Yii::t('main', 'Yhteensä'),
			'saaja_iban' => Yii::t('main', 'Saaja IBAN'),
			'saaja_virtualkoodi' => Yii::t('main', 'Saaja Virtualkoodi'),
			'tilanne' => Yii::t('main', 'Tilanne'),
			'maksettu_euro' => Yii::t('main', 'Maksettu Euro'),
			'hyvityslasku' => Yii::t('main', 'Hyvityslasku'),
			'laskun_nimetys' => Yii::t('main', 'Laskun tyyppi'),
			'response' => Yii::t('main', 'Response'),
			'response_finvoice' => Yii::t('main', 'Response Finvoice'),
			'tapahtumapvm' => Yii::t('main', 'Tapahtuma pvm'),
			'muistutuslasku_auto'=> Yii::t('main', 'Automaattinen muistutuslasku'),
			'kirjeenluokka'=> Yii::t('main', 'Kirjeluokka'),
			'viitenne'=> Yii::t('main', 'Viitteenne'),
			'viitemme'=> Yii::t('main', 'Viitteemme'),
			'freetext'=> Yii::t('main', 'Viesti'),
			'deliverymethod'=> Yii::t('main', 'Toimitustapa'),
			'deliveryterm'=> Yii::t('main', 'Toimitusehto'),
			'vatperiod'=> Yii::t('main', 'Päivämäärä johon ALV kohdistuu'),
			'tuotteet_palvelut_muoto' => Yii::t('main', 'Asiakas vai Hinnasto'),
			'alv_muoto' => Yii::t('main', 'ALV-muoto'),
			'netvisor_dimension_name' => Yii::t('main', 'Kustannuspaikka'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;
		$criteria->order = "id DESC";

		$criteria->compare('id',$this->id);
		$criteria->compare('laskunumero',$this->laskunumero);
		$criteria->compare('lid',$this->lid);
		$criteria->compare('yid',$this->yid);
		$criteria->compare('time',$this->time,true);
		$criteria->compare('tyyppi',$this->tyyppi,true);
		$criteria->compare('yritys',$this->yritys,true);
		$criteria->compare('y_tunnus',$this->y_tunnus,true);
		$criteria->compare('nimi',$this->nimi,true);
		$criteria->compare('as_nro',$this->as_nro);
		$criteria->compare('osoite',$this->osoite,true);
		$criteria->compare('postinumero',$this->postinumero,true);
		$criteria->compare('toimipaikka',$this->toimipaikka,true);
		$criteria->compare('laskutus',$this->laskutus,true);
		$criteria->compare('sahkoposti',$this->sahkoposti,true);
		$criteria->compare('verkkolaskuosoite',$this->verkkolaskuosoite,true);
		$criteria->compare('v_tunnus',$this->v_tunnus,true);
		$criteria->compare('yhteyshenkilo',$this->yhteyshenkilo,true);
		$criteria->compare('nimitarkenne',$this->nimitarkenne,true);
		$criteria->compare('puhelin',$this->puhelin,true);
		$criteria->compare('t_yritys',$this->t_yritys,true);
		$criteria->compare('t_y_tunnus',$this->t_y_tunnus,true);
		$criteria->compare('t_nimi',$this->t_nimi,true);
		$criteria->compare('t_osoite',$this->t_osoite,true);
		$criteria->compare('t_postinumero',$this->t_postinumero,true);
		$criteria->compare('t_toimipaikka',$this->t_toimipaikka,true);
		$criteria->compare('t_puhelin',$this->t_puhelin,true);
		$criteria->compare('t_sahkoposti',$this->t_sahkoposti,true);
		$criteria->compare('toimitusosoite',$this->toimitusosoite,true);
		$criteria->compare('paivays',$this->paivays,true);
		$criteria->compare('erapaiva',$this->erapaiva,true);
		$criteria->compare('toimituspaiva',$this->toimituspaiva,true);
		$criteria->compare('maksuehto',$this->maksuehto,true);
		$criteria->compare('viitenumero',$this->viitenumero,true);
		$criteria->compare('viivastyskorko',$this->viivastyskorko,true);
		$criteria->compare('yhteensa_total_verot',$this->yhteensa_total_verot,true);
		$criteria->compare('yhteensa_total_veroton',$this->yhteensa_total_veroton,true);
		$criteria->compare('yhteensa_total',$this->yhteensa_total,true);
		$criteria->compare('saaja_iban',$this->saaja_iban,true);
		$criteria->compare('saaja_virtualkoodi',$this->saaja_virtualkoodi,true);
		$criteria->compare('tilanne',$this->tilanne,true);
		$criteria->compare('maksettu_euro',$this->maksettu_euro,true);
		$criteria->compare('hyvityslasku',$this->hyvityslasku,true);
		$criteria->compare('laskun_nimetys',$this->laskun_nimetys,true);
		$criteria->compare('response',$this->response,true);
		$criteria->compare('response_finvoice',$this->response_finvoice,true);
		$criteria->compare('tapahtumapvm',$this->tapahtumapvm,true);
		$criteria->compare('muistutuslasku_auto',$this->muistutuslasku_auto,true);
		$criteria->compare('kirjeenluokka',$this->kirjeenluokka,true);
		$criteria->compare('viitenne',$this->viitenne,true);
		$criteria->compare('viitemme',$this->viitemme,true);
		$criteria->compare('freetext',$this->freetext,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	public static function months()
	{
		return [
			1=>Yii::t('main', 'Tammikuu'),
			2=>Yii::t('main', 'Helmikuu'),
			3=>Yii::t('main', 'Maaliskuu'),
			4=>Yii::t('main', 'Huhtikuu'),
			5=>Yii::t('main', 'Toukokuu'),
			6=>Yii::t('main', 'Kesäkuu'),
			7=>Yii::t('main', 'Heinäkuu'),
			8=>Yii::t('main', 'Elokuu'),
			9=>Yii::t('main', 'Syyskuu'),
			10=>Yii::t('main', 'Lokakuu'),
			11=>Yii::t('main', 'Marraskuu'),
			12=>Yii::t('main', 'Joulukuu')
			];
	}

	public static function LaskutetutIDs($ids_muoto, $query)
	{
		$laskut					= Lasku::model()->findAll($query);
		$pre_laskutetut_tiedot	= [];
		$return					= [];
		if(count($laskut) > 0)
		{
			foreach($laskut as $item)
			{
				$laskuRivit			= LaskunRivit::model()->findAll("lid='".$item->id."' AND tiedot IS NOT NULL");
				foreach($laskuRivit as $rivi)
				{
					$get_tiedot = json_decode($rivi->tiedot, true);
					if(isset($get_tiedot[$ids_muoto]))
						$pre_laskutetut_tiedot[] = $get_tiedot[$ids_muoto];
				}
			}

			foreach($pre_laskutetut_tiedot as $item)
			{
				if(is_array($item))
				{
					foreach($item as $k => $id)
						$return[$id] = $id;
				} else {
					$return[$item] = $item;
				}
			}
		}
		
		return $return;
	}

}
